// Generated by CoffeeScript 1.8.0
(function() {
  var Person, d, foo, p;

  foo = function(x) {
    return x * x;
  };

  console.log(foo(5));

  d = function(x) {
    return x + x;
  };

  console.log(d(10));

  Person = (function() {
    function Person(name) {
      this.name = name;
    }

    Person.prototype.getName = function() {
      return console.log(this.name);
    };

    return Person;

  })();

  p = new Person('alex');

  p.getName();

}).call(this);
